version: "3.8"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: saga
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/saga
      INVENTARIO_SERVICE_URL: http://inventario:3001
      PAGOS_SERVICE_URL: http://pagos:3002
      FLASK_ENV: production
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Mock services for testing (optional)
  mock-inventario:
    image: mockserver/mockserver:5.15.0
    ports:
      - "3001:1080"
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/inventario-expectations.json

  mock-pagos:
    image: mockserver/mockserver:5.15.0
    ports:
      - "3002:1080"
    environment:
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/pagos-expectations.json

volumes:
  postgres_data:
