apiVersion: apps/v1
kind: Deployment # Deployment es un controlador que gestiona la creación y actualización de Pods
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2 # cantidad de pods que se desean ejecutar
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
          env:
            - name: UNA_VARIABLE
              value: "patito"
            - name: LA_OTRA_VARIABLE
              value: "FELIZ"
            - name: SALUDITO
              value: "HOLA HOLA GAVILAN SIN COLA"
            - name: IP_DE_MI_NODO # Variable de entorno que obtiene la IP del nodo
              valueFrom:
                fieldRef: # fieldRef se usa para obtener una variable especific del Pod
                  fieldPath: status.hostIP # status.hostIP la IP del nodo donde se ejecuta el Pod
          resources:
            requests:
              memory: "64Mi"
              cpu: "200m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          ports:
            - containerPort: 80
